### ISSUE TITLE
Error in Entity.addValue (module 'entitygraph' has no attribute 'client')

### ISSUE THREAD

**Issue by s3flsago** [mumi/entitygraph-client#5]
Error in version: 0.0.16 (worked with version 0.0.12)

```
collection_serlo_id = URIRef("https://serlo.org/1535")
entity.addValue(OWL.sameAs, collection_serlo_id)
```

Error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 collection_entity = create_collection_entity(
      2     collection_serlo_id, [child_entity_id]
      3 )
      4 print(collection_entity.json())
      5 collection_entity_id = collection_entity.json()[0]["@id"]

Cell In[8], line 8, in create_collection_entity(collection_serlo_id, lr_links)
      6     lr_entity_id = lr_link.split('/')[-1] 
      7     lr_entity = app.Entity().get_by_id(lr_entity_id)
----> 8     collection_entity_builder.addRelation(SDO.hasPart, lr_entity)
     10 collection_entity_builder.addValue(OWL.sameAs, collection_serlo_id)
     12 collection_entity = collection_entity_builder.build()

File [~/venvs/venv01/lib/python3.10/site-packages/entitygraph/entity_builder.py:33](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/asdf/scripts_e365.notebooks/Working-with-the-entity-graph/maintenance/~/venvs/venv01/lib/python3.10/site-packages/entitygraph/entity_builder.py:33), in EntityBuilder.addRelation(self, property, target_entity)
     32 def addRelation(self, property: URIRef, target_entity: Entity):
---> 33     self.graph.add((self.node, property, target_entity.uri))
     35     return self

File [~/venvs/venv01/lib/python3.10/site-packages/entitygraph/entity.py:116](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/asdf/scripts_e365.notebooks/Working-with-the-entity-graph/maintenance/~/venvs/venv01/lib/python3.10/site-packages/entitygraph/entity.py:116), in Entity.uri(self)
    113 @property
    114 def uri(self) -> URIRef:
    115     self.__check_id()
--> 116     base_url: str = entitygraph.client.base_url.rstrip("/")
    117     return URIRef(f"{base_url}/api/s/{self._application_label}/entities/{self._id}")

AttributeError: module 'entitygraph' has no attribute 'client'
```
